### ISSUE TITLE
do you want a mac version of your engine?

### ISSUE THREAD

**Issue by TheDisabledKid** [Tr1NgleDev/Tr1Ngle-Engine#2]
?

**Comment by Tr1NgleDev** [comment]
i dont really know lol. but maybe. after 1.7.0 update that im making. ok?

**Comment by Tr1NgleDev** [comment]
you can add me in discord rn if you want lol
_-Tr1NgleBoss-_#9825

**Comment by TheDisabledKid** [comment]
bet

**Comment by TheDisabledKid** [comment]
ok i sent you a friend request
