### ISSUE TITLE
what happened to the events?

### ISSUE THREAD

**Issue by TheAngelHosko** [Tr1NgleDev/Tr1Ngle-Engine#8]
this is not a problem, it is more like a question, what happened to the events?

**Comment by Tr1NgleDev** [comment]
wdym? events are there. in 1.7 it have own chart editor that you open by pressing 8 in-game
nothing happened to the events.

**Comment by TheAngelHosko** [comment]
Ohh, sorry, I hadn't noticed

**Comment by Tr1NgleDev** [comment]
will close that "issue" now. ok? :)

**Comment by Tr1NgleDev** [comment]
if you have anything to ask. 
there is my discord:
_-Tr1NgleBoss-_#9825
